### ISSUE TITLE
XMLDataError

### ISSUE THREAD

**Issue by badboy-tian** [befinal/node-tenpay#102]
```
receive data =>
<xml>
  <return_code><![CDATA[FAIL]]></return_code>
  <retmsg><![CDATA[请确认请求参数是否正确param mch_id invalid]]></retmsg>
  <retcode><![CDATA[1]]></retcode>
</xml>
```
```
Unhandled Rejection at: Promise  Promise {
  <rejected> Error: XMLDataError
      at Payment._parse (/home/leanengine/app/node_modules/tenpay/lib/index.js:89:51)
      at process._tickCallback (internal/process/next_tick.js:68:7) }  reason:  Error: XMLDataError
    at Payment._parse (/home/leanengine/app/node_modules/tenpay/lib/index.js:89:51)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by befinal** [comment]
报错需要自己做catch处理
