### ISSUE TITLE
微信退款报错

### ISSUE THREAD

**Issue by lofreer** [befinal/node-tenpay#120]
Error: header too long, POST https://api.mch.weixin.qq.com/secapi/pay/refund -1 (connected: false, keepalive socket: false, socketHandledRequests: 0, socketHandledResponses: 0

微信退款报这样的错误

**Comment by lofreer** [comment]
post data =>
<?xml version="1.0"?>
<xml>
  <out_trade_no>1628680244334845</out_trade_no>
  <out_refund_no/>
  <total_fee>NaN</total_fee>
  <refund_fee>1</refund_fee>
  <appid>wx8dc7af47ecbd7ab1</appid>
  <mch_id>1457671102</mch_id>
  <nonce_str>C3SwkzSm1Sk5Tspq</nonce_str>
  <sign_type>MD5</sign_type>
  <op_user_id>1457671102</op_user_id>
  <sign>171092286A2D12D6387DEF0AB4C9887A</sign>
</xml>

{ Error: header too long, POST https://api.mch.weixin.qq.com/secapi/pay/refund -1 (connected: false, keepalive socket: false, socketHandledRequests: 0, socketHandledResponses: 0)
headers: {}
    at Object.createSecureContext (_tls_common.js:210:19)
    at Object.connect (_tls_wrap.js:1130:48)
    at Agent.createConnection (https.js:120:22)
    at Agent.createSocket (_http_agent.js:227:26)
    at Agent.addRequest (_http_agent.js:185:10)
    at new ClientRequest (_http_client.js:258:16)
    at Object.request (https.js:289:10)
    at Object.requestWithCallback (/home/appuser/server/box-api/node_modules/urllib/lib/urllib.js:1013:19)
    at /home/appuser/server/box-api/node_modules/urllib/lib/urllib.js:162:13
    at new Promise (<anonymous>)
    at Object.request (/home/appuser/server/box-api/node_modules/urllib/lib/urllib.js:161:10)
    at Payment._request (/home/appuser/server/box-api/node_modules/tenpay/lib/index.js:195:39)
    at Payment.refund (/home/appuser/server/box-api/node_modules/tenpay/lib/index.js:433:17)
    at WechatPayService.refund (/home/appuser/server/box-api/app/service/tools/wechatPay.js:123:40)
    at MemberOrderService.undo (/home/appuser/server/box-api/app/service/member/memberOrder.js:704:44)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  data: undefined,
  path: '/secapi/pay/refund',
  status: -1,
  headers: {},
  res:
   { status: -1,
     statusCode: -1,
     statusMessage: null,
     headers: {},
     size: 0,
     aborted: false,
     rt: 1,
     keepAliveSocket: false,
     data: undefined,
     requestUrls: [ 'https://api.mch.weixin.qq.com/secapi/pay/refund' ],
     timing: null,
     remoteAddress: '',
     remotePort: '',
     socketHandledRequests: 0,
     socketHandledResponses: 0 } }

微信退款报这样的错误

**Comment by Xujalg** [comment]
请问如何解决的？

**Comment by befinal** [comment]
查看证书是否正确，退款需要证书

**Comment by Xujalg** [comment]
> 查看证书是否正确，退款需要证书

是的 这个问题是因为证书错误导致的
