### ISSUE TITLE
XML格式错误

### ISSUE THREAD

**Issue by TrinityHC** [befinal/node-tenpay#26]
```
router.post('/', function (req, res, next) {
  let openid = req.body.openid
  let products = req.body.products
  let totalAmount = req.body.totalAmount
  let address = req.body.address
  Customer.findOne({openid:openid}, function(err, customer){
    if(customer){
      let order = new Order({
        user: customer._id,
        phone: customer.phone,
        items: products,
        totalAmount: totalAmount,
        shippingAddress: address,
        status: 'created',
        createdAt: new Date().getTime(),
        updatedAt: new Date().getTime()
      })
      order.save((err, order)=>{
        if(order){
          let result = unifiedOrder(order._id, '服装', totalAmount,customer.openId)
          console.log(result)
          return res.send(result)
       }
     })
    }
  })
})


async function unifiedOrder(orderId, name, totalAmount, openid){
  try {
    let result = await wxpay.unifiedOrder({
      out_trade_no: orderId,
      body: name,
      total_fee: totalAmount,
      openid: openid
    });
    console.log(result)
  } catch (error) {
    console.error(error);
  }
}
```

Error Console
`Promise { <pending> }
Error: XML格式错误
    at Payment._parse (/Users/haochen/wechat/kunkka/node_modules/tenpay/lib/index.js:43:47)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)`

不太清楚那里出错了 才会导致返回xml格式错误？在local做测试时返回的

**Comment by TrinityHC** [comment]
不好意思 找到错误了，商户订单号填错了
