### ISSUE TITLE
调用refund接口报错

### ISSUE THREAD

**Issue by PanZhangOne** [befinal/node-tenpay#37]
```
{ResponseError: socket hang up (req "error"), POST https://api.mch.weixin.qq.com/secapi/pay/refund -1 (connected: true, keepalive socket: false)
headers: {}
    at createHangUpError (_http_client.js:331:15)
    at TLSSocket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at Payment.request (C:\project\nextown\nodejs-nextown-api\node_modules\tenpay\lib\index.js:282:10)
    at Payment.refund (C:\project\nextown\nodejs-nextown-api\node_modules\tenpay\lib\index.js:136:15)
    at Finance.refundDispatchOrder (C:\project\nextown\nodejs-nextown-api\src\models\finance.js:40:41)
    at <anonymous>
  code: 'ECONNRESET',
  name: 'ResponseError',
  data: undefined,
  path: '/secapi/pay/refund',
  status: 500,
  headers: {},
  res:
   { status: -1,
     statusCode: 500,
     headers: {},
     size: 0,
     aborted: false,
     rt: 216,
     keepAliveSocket: false,
     data: undefined,
     requestUrls: [ 'https://api.mch.weixin.qq.com/secapi/pay/refund' ],
     timing: null,
     remoteAddress: '182.254.78.168',
     remotePort: 443 } }
```

在调用退款接口时出现如下错误，请怎么回事啊

tenpay版本:1.1.4
node版本:8.11.1

**Comment by befinal** [comment]
升级版本试试
npm i tenpay@latest

**Comment by PanZhangOne** [comment]
@befinal 升级到最新版本后，依然出现这个问题😂

**Comment by befinal** [comment]
证书配置对了吗?

**Comment by PanZhangOne** [comment]
是证书配置出错了😂，麻烦了

**Comment by zhenghan-fsd** [comment]
你好@PanZhangOne 证书是怎么配置的？

**Comment by lzl** [comment]
本地测试和部署到测试服务器时，报了和楼主发的一模一样的错，可是我没发现证书配置有什么遗漏。

```js
pfx: require('fs').readFileSync('./apiclient_cert.p12'), // 证书文件路径
```

如果我修改了路径，服务器会因为找不到文件而无法启动。

@PanZhangOne 请问当时你是如何排查的。

@befinal 我在证书配置方面是否存在遗漏。

**Comment by PanZhangOne** [comment]
@lzl 我们有两个公众号证书，错误地使用了另一个

**Comment by lzl** [comment]
@PanZhangOne 是微信支付的API证书，对吧。

**Comment by lzl** [comment]
```
apiclient_cert.p12
apiclient_cert.pem
apiclient_key.pem
```

这三个证书，应该用哪个？

**Comment by lzl** [comment]
解密 https://github.com/jxtech/wechatpy/issues/312
导入 https://www.cnblogs.com/stoneniqiu/p/5585451.html

两个法子都试过了，报错依旧。

**Comment by befinal** [comment]
使用P12证书.查检证书路径是不是正确,或者使用绝对路径先尝试一下

**Comment by lzl** [comment]
原因找到了。

我把源码里的 `this.pfx` 打出来，发现是 `undefined`，说明证书压根没赋上。原因是我先把证书赋给了配置参数，再把配置参数传给 `tenpay`，可能是在这个过程中出现问题了。改为初始化时直接传给 `tenpay` 就好了。

```js
const config = {
  appid: wechatConfig.appId,
  mchid: wechatConfig.mchId,
  partnerKey: wechatConfig.mchKey,
  // pfx: wechatConfig.pfs, // 这样就报错
  pfx: require('fs').readFileSync('./apiclient_cert.p12'), // 改为直接读取
  notify_url: wechatConfig.notify_url,
  refund_url: wechatConfig.refund_url,
}
```

**Comment by Primary-Traxex** [comment]
遇到相同的问题， @lzl 你的方法用了也是不行。
后来我直接在源码里面配置
在node_modules=>tenpay=>lib=>index.js文件里
`this.pfx = require('fs').readFileSync('./apiclient_cert.p12');`
就可以正常用了

**Comment by befinal** [comment]
先使用一个变量保存文件buffer
然后再实例化试试。
空值的话应该是证书还没有读取完成就实例化了

**Comment by badboy-tian** [comment]
我今天遇到这个问题了 打印pfx是能打印东西的 虽然是乱码 找不到头绪 突发情况的
