### ISSUE TITLE
server error Error: ORDERPAID

### ISSUE THREAD

**Issue by kevin1942** [befinal/node-tenpay#55]
server error Error: ORDERPAID
    at Payment._parse (E:\nodeproject\everprint\node_modules\_tenpay@2.1.6@tenpay\lib\index.js:74:51)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) { request: ~~~~~
这个是已经支付过了的意思吗?是腾讯返回的吗?

**Comment by befinal** [comment]
这个是已经支付成功了
