### ISSUE TITLE
sendCoupon Sign 签名错误

### ISSUE THREAD

**Issue by ash0080** [befinal/node-tenpay#61]
```
<rejected> Error: sign签名错误
    at Payment._parse (/home/leanengine/app/node_modules/tenpay/lib/index.js:102:70)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) }  reason:  Error: sign签名错误
    at Payment._parse (/home/leanengine/app/node_modules/tenpay/lib/index.js:102:70)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
请求超时: url=/wx/rewards, timeout=30000, 请确认方法执行耗时很长，或没有正确的 response 回调。
```
提示错误，但其实我已经发成功并领到了

这是怎么回事？

版本 2.1.7

**Comment by befinal** [comment]
能否使用debug方式开启调试模式
查看一下发送代金券时微信方的返回数据信息是否和文档一致吧
这个错误应该是由于微信方返回的信息校验不通过导致的, 有可能是BUG, 也有可能是微信的返回值和文档不一致造成的.

**Comment by befinal** [comment]
实例化时将第二个默认参数设置为true可以在发送数据和微信返回时在控制台进行输出. 可否查看微信的返回信息并贴一下, 通过_getSign方法来验证一下返回的签名是否能通过?
`
const api = new tenpay(config, true);
`

**Comment by ash0080** [comment]
好的 稍晚点我尝试贴一下 这个其实已经发成功了，
刚试了一下, 不成功返回错误代码的情况下倒是正常，比如我再次领取返回USER_AL_GET_COUPON，并且也没有报错

**Comment by ash0080** [comment]
```
post data =>
<?xml version="1.0"?>
<xml>
  <coupon_stock_id>9242601</coupon_stock_id>
  <partner_trade_no>149635878220180822165906719</partner_trade_no>
  <appid></appid>
  <mch_id></mch_id>
  <nonce_str></nonce_str>
  <openid_count>1</openid_count>
  <sign></sign>
</xml>

//  第一次， 领券
receive data =>
<xml>
<return_code><![CDATA[SUCCESS]]></return_code>
<appid><![CDATA[]]></appid>
<mch_id><![CDATA[]]></mch_id>
<device_info><![CDATA[]]></device_info>
<nonce_str><![CDATA[]]></nonce_str>
<result_code><![CDATA[SUCCESS]]></result_code>
<coupon_stock_id><![CDATA[9242601]]></coupon_stock_id>
<resp_count><![CDATA[1]]></resp_count>
<success_count><![CDATA[1]]></success_count>
<failed_count><![CDATA[0]]></failed_count>
<openid><![CDATA[-2qKA]]></openid>
<coupon_id><![CDATA[3987564310]]></coupon_id>
<partner_trade_no><![CDATA[149635878220180822165906719]]></partner_trade_no>
</xml>

// 第二次，领过了
<xml>
<return_code><![CDATA[SUCCESS]]></return_code>
<return_msg><![CDATA[]]></return_msg>
<appid><![CDATA[]]></appid>
<mch_id><![CDATA[]]></mch_id>
<device_info><![CDATA[]]></device_info>
<nonce_str><![CDATA[]]></nonce_str>
<err_code><![CDATA[USER_AL_GET_COUPON]]></err_code>
<err_code_des><![CDATA[你已领取过该代金券]]></err_code_des>
<resp_count><![CDATA[1]]></resp_count>
<success_count><![CDATA[0]]></success_count>
<failed_count><![CDATA[1]]></failed_count>
<openid><![CDATA[-2qKA]]></openid>
<ret_code><![CDATA[FAIL]]></ret_code>
<ret_msg><![CDATA[你已领取过该代金券]]></ret_msg>
<partner_trade_no><![CDATA[149635878220180822170126797]]></partner_trade_no>
</xml>
```


这样 两次都抛出异常了

**Comment by befinal** [comment]
这个暂时设计是这样的, 不然的话对于所有情况都要对正确结果和错误结果进行2次包装, 使用者仍然需要根据err_code的情况去判断实际结果, 和使用try/catch是一样的效果, 而且这样便于统一管理.

因为本身支付是涉及财务相关的, 对于所有非预期的其它返回都应该进行异常判断以保证可靠性.

**Comment by ash0080** [comment]
挺奇怪 看了下源码  感觉 sendCoupon 应该不会抛出json.err_code的异常才对

**Comment by befinal** [comment]
确实也可以, 我再考虑一下什么样的处理方式比较好
至于之前那个sign的问题, 你可以先fork一下, 然后自己处理一下api类型忽略掉sign验证
后续版本我会fix
