### ISSUE TITLE
调用沙盒实例的企业支付接口时候报错

### ISSUE THREAD

**Issue by lltxwdk** [befinal/node-tenpay#87]
Error: wrong tag, POST https://api.mch.weixin.qq.com/sandboxnew/mmpaymkttransfers/promotion/transfers -1 (connected: false, keepalive socket: false, socketHandledRequests: 0, socketHandledResponses: 0)

data:undefined
headers:Object {}
message:"wrong tag, POST https://api.mch.weixin.qq.com/sandboxnew/mmpaymkttransfers/promotion/transfers -1 (connected: false, keepalive socket: false, socketHandledRequests: 0, socketHandledResponses: 0)\nheaders: {}"
path:"/sandboxnew/mmpaymkttransfers/promotion/transfers"
stack:"Error: wrong tag, POST https://api.mch.weixin.qq.com/sandboxnew/mmpaymkttransfers/promotion/transfers -1 (connected: false, keepalive socket: false, socketHandledRequests: 0, socketHandledResponses: 0)\nheaders: {}\n    at Object.createSecureContext (_tls_common.js:200:19)\n    at Object.exports.connect (_tls_wrap.js:1119:48)\n    at Agent.createConnection (https.js:119:22)\n    at Agent.createSocket (_http_agent.js:227:26)\n    at Agent.addRequest (_http_agent.js:185:10)\n    at new ClientRequest (_http_client.js:239:16)\n    at Object.request (https.js:272:10)\n    at Object.requestWithCallback (/Users/lilei/moon-admin-services/m-admin-services/node_modules/_urllib@2.30.0@urllib/lib/urllib.js:867:19)\n    at /Users/lilei/moon-admin-services/m-admin-services/node_modules/_urllib@2.30.0@urllib/lib/urllib.js:150:13\n    at new Promise (<anonymous>)\n    at Object.request (/Users/lilei/moon-admin-services/m-admin-services/node_modules/_urllib@2.30.0@urllib/lib/urllib.js:149:10)\n    at Payment._request (/Users/lilei/moon-a...
status:-1
__proto__:Object {constructor: , name: "Error", message: "", …}
wrong tag, POST https://api.mch.weixin.qq.com/sandboxnew/mmpaymkttransfers/promotion/transfers -1 (connected: false, keepalive socket: false, socketHandledRequests: 0, socketHandledResponses: 0)
context.js:38
headers: {}

**Comment by lltxwdk** [comment]
已解决，证书问题p12
